//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace winPEAS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("winPEAS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call a COM object.
        /// </summary>
        internal static string ActionTypeComHandler {
            get {
                return ResourceManager.GetString("ActionTypeComHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a program.
        /// </summary>
        internal static string ActionTypeExecute {
            get {
                return ResourceManager.GetString("ActionTypeExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send an e-mail.
        /// </summary>
        internal static string ActionTypeSendEmail {
            get {
                return ResourceManager.GetString("ActionTypeSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display a message.
        /// </summary>
        internal static string ActionTypeShowMessage {
            get {
                return ResourceManager.GetString("ActionTypeShowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {3} {0:P}.
        /// </summary>
        internal static string ComHandlerAction {
            get {
                return ResourceManager.GetString("ComHandlerAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every day.
        /// </summary>
        internal static string DOWAllDays {
            get {
                return ResourceManager.GetString("DOWAllDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} {0}.
        /// </summary>
        internal static string EmailAction {
            get {
                return ResourceManager.GetString("EmailAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string EndSentence {
            get {
                return ResourceManager.GetString("EndSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date and time a trigger expires must be later than the time time it starts or is activated..
        /// </summary>
        internal static string Error_TriggerEndBeforeStart {
            get {
                return ResourceManager.GetString("Error_TriggerEndBeforeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string ExecAction {
            get {
                return ResourceManager.GetString("ExecAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string HyphenSeparator {
            get {
                return ResourceManager.GetString("HyphenSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        internal static string ListSeparator {
            get {
                return ResourceManager.GetString("ListSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every month.
        /// </summary>
        internal static string MOYAllMonths {
            get {
                return ResourceManager.GetString("MOYAllMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple actions defined.
        /// </summary>
        internal static string MultipleActions {
            get {
                return ResourceManager.GetString("MultipleActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple triggers defined.
        /// </summary>
        internal static string MultipleTriggers {
            get {
                return ResourceManager.GetString("MultipleTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string ShowMessageAction {
            get {
                return ResourceManager.GetString("ShowMessageAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string TaskDefaultPrincipal {
            get {
                return ResourceManager.GetString("TaskDefaultPrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string TaskStateDisabled {
            get {
                return ResourceManager.GetString("TaskStateDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued.
        /// </summary>
        internal static string TaskStateQueued {
            get {
                return ResourceManager.GetString("TaskStateQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string TaskStateReady {
            get {
                return ResourceManager.GetString("TaskStateReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string TaskStateRunning {
            get {
                return ResourceManager.GetString("TaskStateRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string TaskStateUnknown {
            get {
                return ResourceManager.GetString("TaskStateUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to any user.
        /// </summary>
        internal static string TriggerAnyUser {
            get {
                return ResourceManager.GetString("TriggerAnyUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At system startup.
        /// </summary>
        internal static string TriggerBoot1 {
            get {
                return ResourceManager.GetString("TriggerBoot1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Trigger.
        /// </summary>
        internal static string TriggerCustom1 {
            get {
                return ResourceManager.GetString("TriggerCustom1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At {0:t} every day.
        /// </summary>
        internal static string TriggerDaily1 {
            get {
                return ResourceManager.GetString("TriggerDaily1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At {0:t} every {1} days.
        /// </summary>
        internal static string TriggerDaily2 {
            get {
                return ResourceManager.GetString("TriggerDaily2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indefinitely.
        /// </summary>
        internal static string TriggerDuration0 {
            get {
                return ResourceManager.GetString("TriggerDuration0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for a duration of {0}.
        /// </summary>
        internal static string TriggerDurationNot0 {
            get {
                return ResourceManager.GetString("TriggerDurationNot0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for {0}.
        /// </summary>
        internal static string TriggerDurationNot0Short {
            get {
                return ResourceManager.GetString("TriggerDurationNot0Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger expires at {0:G}..
        /// </summary>
        internal static string TriggerEndBoundary {
            get {
                return ResourceManager.GetString("TriggerEndBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom event filter.
        /// </summary>
        internal static string TriggerEvent1 {
            get {
                return ResourceManager.GetString("TriggerEvent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On event - Log: {0}.
        /// </summary>
        internal static string TriggerEventBasic1 {
            get {
                return ResourceManager.GetString("TriggerEventBasic1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , Source: {0}.
        /// </summary>
        internal static string TriggerEventBasic2 {
            get {
                return ResourceManager.GetString("TriggerEventBasic2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , EventID: {0}.
        /// </summary>
        internal static string TriggerEventBasic3 {
            get {
                return ResourceManager.GetString("TriggerEventBasic3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When computer is idle.
        /// </summary>
        internal static string TriggerIdle1 {
            get {
                return ResourceManager.GetString("TriggerIdle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At log on of {0}.
        /// </summary>
        internal static string TriggerLogon1 {
            get {
                return ResourceManager.GetString("TriggerLogon1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At {0:t} on day {1} of {2}, starting {0:d}.
        /// </summary>
        internal static string TriggerMonthly1 {
            get {
                return ResourceManager.GetString("TriggerMonthly1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At {0:t} on {1} {2:f} each {3}, starting {0:d}.
        /// </summary>
        internal static string TriggerMonthlyDOW1 {
            get {
                return ResourceManager.GetString("TriggerMonthlyDOW1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the task is created or modified.
        /// </summary>
        internal static string TriggerRegistration1 {
            get {
                return ResourceManager.GetString("TriggerRegistration1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After triggered, repeat every {0} {1}..
        /// </summary>
        internal static string TriggerRepetition {
            get {
                return ResourceManager.GetString("TriggerRepetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every {0} {1}..
        /// </summary>
        internal static string TriggerRepetitionShort {
            get {
                return ResourceManager.GetString("TriggerRepetitionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On local connection to {0}..
        /// </summary>
        internal static string TriggerSessionConsoleConnect {
            get {
                return ResourceManager.GetString("TriggerSessionConsoleConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On local disconnect from {0}..
        /// </summary>
        internal static string TriggerSessionConsoleDisconnect {
            get {
                return ResourceManager.GetString("TriggerSessionConsoleDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On remote connection to {0}..
        /// </summary>
        internal static string TriggerSessionRemoteConnect {
            get {
                return ResourceManager.GetString("TriggerSessionRemoteConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On remote disconnect from {0}..
        /// </summary>
        internal static string TriggerSessionRemoteDisconnect {
            get {
                return ResourceManager.GetString("TriggerSessionRemoteDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On workstation lock of {0}..
        /// </summary>
        internal static string TriggerSessionSessionLock {
            get {
                return ResourceManager.GetString("TriggerSessionSessionLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On workstation unlock of {0}..
        /// </summary>
        internal static string TriggerSessionSessionUnlock {
            get {
                return ResourceManager.GetString("TriggerSessionSessionUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user session of {0}.
        /// </summary>
        internal static string TriggerSessionUserSession {
            get {
                return ResourceManager.GetString("TriggerSessionUserSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At {0:t} on {0:d}.
        /// </summary>
        internal static string TriggerTime1 {
            get {
                return ResourceManager.GetString("TriggerTime1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At startup.
        /// </summary>
        internal static string TriggerTypeBoot {
            get {
                return ResourceManager.GetString("TriggerTypeBoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Trigger.
        /// </summary>
        internal static string TriggerTypeCustom {
            get {
                return ResourceManager.GetString("TriggerTypeCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string TriggerTypeDaily {
            get {
                return ResourceManager.GetString("TriggerTypeDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On an event.
        /// </summary>
        internal static string TriggerTypeEvent {
            get {
                return ResourceManager.GetString("TriggerTypeEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On idle.
        /// </summary>
        internal static string TriggerTypeIdle {
            get {
                return ResourceManager.GetString("TriggerTypeIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At log on.
        /// </summary>
        internal static string TriggerTypeLogon {
            get {
                return ResourceManager.GetString("TriggerTypeLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string TriggerTypeMonthly {
            get {
                return ResourceManager.GetString("TriggerTypeMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string TriggerTypeMonthlyDOW {
            get {
                return ResourceManager.GetString("TriggerTypeMonthlyDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At task creation/modification.
        /// </summary>
        internal static string TriggerTypeRegistration {
            get {
                return ResourceManager.GetString("TriggerTypeRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On state change.
        /// </summary>
        internal static string TriggerTypeSessionStateChange {
            get {
                return ResourceManager.GetString("TriggerTypeSessionStateChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One time.
        /// </summary>
        internal static string TriggerTypeTime {
            get {
                return ResourceManager.GetString("TriggerTypeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string TriggerTypeWeekly {
            get {
                return ResourceManager.GetString("TriggerTypeWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At {0:t} every {1} of every week, starting {0:d}.
        /// </summary>
        internal static string TriggerWeekly1Week {
            get {
                return ResourceManager.GetString("TriggerWeekly1Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At {0:t} every {1} of every {2} weeks, starting {0:d}.
        /// </summary>
        internal static string TriggerWeeklyMultWeeks {
            get {
                return ResourceManager.GetString("TriggerWeeklyMultWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every.
        /// </summary>
        internal static string WWAllWeeks {
            get {
                return ResourceManager.GetString("WWAllWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fifth.
        /// </summary>
        internal static string WWFifthWeek {
            get {
                return ResourceManager.GetString("WWFifthWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first.
        /// </summary>
        internal static string WWFirstWeek {
            get {
                return ResourceManager.GetString("WWFirstWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourth.
        /// </summary>
        internal static string WWFourthWeek {
            get {
                return ResourceManager.GetString("WWFourthWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last.
        /// </summary>
        internal static string WWLastWeek {
            get {
                return ResourceManager.GetString("WWLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        internal static string WWSecondWeek {
            get {
                return ResourceManager.GetString("WWSecondWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to third.
        /// </summary>
        internal static string WWThirdWeek {
            get {
                return ResourceManager.GetString("WWThirdWeek", resourceCulture);
            }
        }
    }
}
